export const GEMINI_URL = key =>
  `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${key}`;

export const ELEMENT_TYPES = [
  "input","password","email","button","link","dropdown",
  "checkbox","radio","textarea","form","table","modal","search","custom"
];

export const T = {
  // Sidebar — deep blue
  sidebar:     "#1e3a5f",
  sidebarHov:  "#162d4a",
  sidebarBorder:"#2a4a73",
  sidebarText: "#e2eaf4",
  sidebarSub:  "#8baac8",
  sidebarActive:"#3b82f6",

  // Main content — light
  bg:        "#e8edf3",
  bg1:       "#ffffff",
  bg2:       "#f1f5f9",
  bg3:       "#e2e8f0",
  border:    "#e2e8f0",
  text:      "#0f172a",
  text2:     "#334155",
  text3:     "#64748b",
  accent:    "#2563eb",
  accentHov: "#1d4ed8",
  green:     "#16a34a",
  red:       "#dc2626",
  amber:     "#d97706",
  blue:      "#2563eb",
};

export function uid() { return Math.random().toString(36).slice(2, 9); }

export function fileToB64(file) {
  return new Promise((res, rej) => {
    const r = new FileReader();
    r.onload = () => res(r.result.split(",")[1]);
    r.onerror = () => rej(new Error("Read failed"));
    r.readAsDataURL(file);
  });
}

export function extractElementsFromHTML(html) {
  try {
    const doc = new DOMParser().parseFromString(html, "text/html");
    const found = [];
    const selectors = [
      { tags: ["input[type='text']", "input:not([type])"], type: "input" },
      { tags: ["input[type='password']"], type: "password" },
      { tags: ["input[type='email']"], type: "email" },
      { tags: ["input[type='checkbox']"], type: "checkbox" },
      { tags: ["input[type='radio']"], type: "radio" },
      { tags: ["button", "input[type='submit']", "input[type='button']"], type: "button" },
      { tags: ["select"], type: "dropdown" },
      { tags: ["textarea"], type: "textarea" },
      { tags: ["a[href]"], type: "link" },
    ];
    selectors.forEach(({ tags: tgs, type }) => {
      tgs.forEach(sel => {
        doc.querySelectorAll(sel).forEach((el, i) => {
          const id = el.id || el.name || "";
          const label = el.placeholder || el.innerText?.trim()?.slice(0, 40)
            || el.getAttribute("aria-label") || el.name
            || el.id || `${type}_${i + 1}`;
          if (!label || label.length > 60) return;
          const xpath = id ? `//${el.tagName.toLowerCase()}[@id='${id}']`
                           : `//${el.tagName.toLowerCase()}[${i + 1}]`;
          found.push({ uid: uid(), label: label.trim(), type, id, xpath,
            locator: id ? `id=${id}` : xpath, description: `Auto-extracted ${type}` });
        });
      });
    });
    const seen = new Set();
    return found.filter(e => { if (seen.has(e.id+e.label)) return false; seen.add(e.id+e.label); return true; });
  } catch { return []; }
}

export async function callGemini(apiKey, parts) {
  const res = await fetch(GEMINI_URL(apiKey), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [{ parts }],
      generationConfig: { temperature: 0.2, maxOutputTokens: 6000 }
    })
  });
  const data = await res.json();
  if (data.error) throw new Error(data.error.message);
  return data.candidates?.[0]?.content?.parts?.[0]?.text || "";
}

export function buildRobotFile(project, page, testCases, keywords, browserMode) {
  const headless = browserMode === "headless" ? "True" : "False";
  const fname = (page.name || "suite").replace(/\s+/g, "_");
  let out = `*** Settings ***
Documentation     ${page.name} — Generated by QAMS QA Robot
...               Project: ${project.name} | URL: ${page.url || project.baseUrl}
Library           Browser
Suite Setup       Open Application
Suite Teardown    Close All Browsers

*** Variables ***
\${APP_URL}         ${page.url || project.baseUrl || "https://your-app.com"}
\${BROWSER}         chromium
\${HEADLESS}        ${headless}
\${SS_DIR}          \${OUTPUT_DIR}/screenshots/${fname}
\${TIMEOUT}         15s

*** Test Cases ***\n`;

  testCases.forEach(tc => {
    out += `\n${tc.name}\n`;
    out += `    [Documentation]    ${tc.documentation}\n`;
    out += `    [Tags]             ${(tc.tags || []).join("    ")}\n`;
    out += `    [Setup]            Navigate To App    ${page.url || project.baseUrl || "\${APP_URL}"}\n`;
    out += `    [Teardown]         Run Keyword If Test Failed    Take Screenshot    \${SS_DIR}/${tc.name.replace(/\s+/g, "_")}_FAIL.png\n`;
    (tc.steps || []).forEach(s => { out += `    ${s}\n`; });
    out += `    Take Screenshot    \${SS_DIR}/${tc.name.replace(/\s+/g, "_")}_done.png\n`;
  });

  out += `\n*** Keywords ***\n\nOpen Application\n    [Documentation]    Launch browser and open app\n    New Browser    \${BROWSER}    headless=\${HEADLESS}\n    New Context    viewport={'width': 1280, 'height': 720}\n    New Page    \${APP_URL}\n    Set Browser Timeout    \${TIMEOUT}\n\nNavigate To App\n    [Arguments]    \${url}=\${APP_URL}\n    [Documentation]    Navigate to given URL\n    New Page    \${url}\n    Take Screenshot    \${SS_DIR}/page_loaded.png\n\n`;

  (keywords || []).forEach(kw => {
    out += `${kw.name}\n`;
    if (kw.doc) out += `    [Documentation]    ${kw.doc}\n`;
    if (kw.args?.length) out += `    [Arguments]    ${kw.args.join("    ")}\n`;
    (kw.steps || []).forEach(s => { out += `    ${s}\n`; });
    out += "\n";
  });
  return out;
}

export function buildXML(project, page, testCases) {
  const now = new Date().toISOString();
  let xml = `<?xml version="1.0" encoding="UTF-8"?>\n<robot generator="QAMS-QA-Robot" generated="${now}">\n  <suite name="${page.name}">\n    <doc>Project: ${project.name}</doc>\n`;
  testCases.forEach((tc, i) => {
    xml += `    <test id="s1-t${i+1}" name="${tc.name}">\n      <doc>${tc.documentation}</doc>\n      <tags>\n`;
    (tc.tags||[]).forEach(tag => { xml += `        <tag>${tag}</tag>\n`; });
    xml += `      </tags>\n`;
    (tc.steps||[]).forEach(step => {
      const parts = step.split(/\s{2,}/);
      xml += `      <kw name="${parts[0]||step}">\n`;
      parts.slice(1).forEach(arg => { xml += `        <arg>${arg}</arg>\n`; });
      xml += `      </kw>\n`;
    });
    xml += `      <status status="NOT RUN" starttime="${now}" endtime="${now}"/>\n    </test>\n`;
  });
  xml += `  </suite>\n</robot>\n`;
  return xml;
}

export function buildCSV(project, page, testCases) {
  const rows = [["Test Case Name","Type","Documentation","Tags","Step No","Step","Locator","Expected Result"]];
  testCases.forEach(tc => {
    (tc.steps||[]).forEach((step, i) => {
      rows.push([
        i===0?tc.name:"", i===0?tc.type:"", i===0?tc.documentation:"",
        i===0?(tc.tags||[]).join(", "):"", i+1, step,
        step.includes("id=")?step.match(/id=[\w-]+/)?.[0]||"":"",
        step.startsWith("Should")||step.startsWith("Get Text")?step:""
      ]);
    });
    rows.push(["","","","","","","",""]);
  });
  return rows.map(row => row.map(cell => `"${String(cell).replace(/"/g,'""')}"`).join(",")).join("\n");
}
